language: elixir

elixir:
  - 1.2.3
otp_release:
  - 18.2.1

env:
  - MIX_ENV=test
  - TRAVIS_NODE_VERSION="4"

sudo: false # faster builds

notifications:
  email:
    - dwr@codingbox.io

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - psql -c 'create database lyn_test;' -U postgres
