language: elixir

elixir:
  - 1.2.3
otp_release:
  - 18.2.1

env: MIX_ENV=test

sudo: false # faster builds

notifications:
  email: false

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database lyn_test;' -U postgres
